# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: IS/grpc/transaction_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'IS/grpc/transaction_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!IS/grpc/transaction_service.proto\"!\n\x0eStringResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\x0cQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\x83\x02\n\x12TransactionService\x12*\n\x0f\x43onvertCSVToXML\x12\x06.Empty\x1a\x0f.StringResponse\x12\x32\n\x17GetFirstTwoTransactions\x12\x06.Empty\x1a\x0f.StringResponse\x12&\n\x0bValidateXML\x12\x06.Empty\x1a\x0f.StringResponse\x12-\n\x0bQueryByCity\x12\r.QueryRequest\x1a\x0f.StringResponse\x12\x36\n\x14QueryByTransactionID\x12\r.QueryRequest\x1a\x0f.StringResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'IS.grpc.transaction_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STRINGRESPONSE']._serialized_start=37
  _globals['_STRINGRESPONSE']._serialized_end=70
  _globals['_QUERYREQUEST']._serialized_start=72
  _globals['_QUERYREQUEST']._serialized_end=101
  _globals['_EMPTY']._serialized_start=103
  _globals['_EMPTY']._serialized_end=110
  _globals['_TRANSACTIONSERVICE']._serialized_start=113
  _globals['_TRANSACTIONSERVICE']._serialized_end=372
# @@protoc_insertion_point(module_scope)
